name: Run Tests

concurrency:
  group: run-tests-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install -g ajv-cli
      - name: Run tests
        run: |
          ajv validate -s priority.schema.json -d priority.json

